### ISSUE TITLE
openai compatible endpoints support

### ISSUE THREAD

**Issue by nijisakai** [mimrock/Bartender#3]
thanks for the great tool. working great on rocket.chat 6.6.6.

I'm wondering if it's possible to support more llms? i had served some local llms so if it's ok to add the feature to use them through api like [litellm](https://litellm.vercel.app/docs/providers/openai_compatible)?

**Comment by mimrock** [comment]
I can see you closed this as completed, but if someone else finds the thread, you should be able to use any OpenAI-compatible endpoints. Just change the `HostName` and the `Completion` and `Moderation` endpoint path in the config file: https://github.com/mimrock/Bartender/blob/master/config.yaml.default#L10

**Comment by nijisakai** [comment]
I did solved it using self-hosted OpenAI-compatible endpoints [oneapi](https://github.com/songquanpeng/one-api), [portkey.ai](https://portkey.ai/) may also work.
For using this by local url, I rebuild the project, change `https` to `http` in /openai/openai.go.

**Comment by mimrock** [comment]
It is true that missing http support can make things more complex in a locally hosted system. Thanks for the feedback, I'll see if I can do something about this in a future release.
